### ISSUE TITLE
Some example would help

### ISSUE THREAD

**Issue by KoinBanks** [dlueth/qoopido.demand#4]
Hey, I'm trying this library but I'm having a hard time understanding how to set it up for the first time.

Any actual example would be great!

**Comment by KoinBanks** [comment]
Particular example - in `Loading demand option #1`

I load the script before closing <body> tag. 
Got the inline configuration like:

```
("dist/demand.js", "app/main", {
      base: "./",
      version: "1.0.0",
      cache: false,
    })
```

Yet nothing happens with `app/main.js` file, it's not even attempting to load it in network tab.

My `app/main.js` file looks like your default example: 

```
(function(global) {
	'use strict';

	function definition(demand, provide) {
		demand
			.configure({
				// any option from the previous section
				// most likely something like:
				pattern: {
				},
				modules: {
				}
			});

		return true; // just return true if there really is nothing to return
	}

	provide([ 'demand', 'provide' ], definition);
}(this));
```

What am I doing wrong?

**Comment by KoinBanks** [comment]
Tried different web server - this time https://www.npmjs.com/package/http-server

Started it with command `http-server --cors` and now I'm getting this in console:

![image](https://user-images.githubusercontent.com/12659034/89421590-8356da80-d734-11ea-99bc-f3a88f345c3d.png)

There is also no sign of app/main.js being loaded.

**Comment by dlueth** [comment]
@iFarmGolems Thanks for your report! Would you be able to setup a dummy repo with minimal, yet complete code? I know initial setup is a bit hard to deal with but I'll sure help you sort things out ;)

**Comment by dlueth** [comment]
@iFarmGolems I was able to reproduce the issue I think, no need for a minimal repo from your side. I am looking into it ;)

**Comment by dlueth** [comment]
@iFarmGolems Found the problem: I forgot to update the README.md with the latest changes regarding path resolution. In your case, simply change your first snippet part to

```
("dist/demand.js", "./app/main", {
      base: "./",
      version: "1.0.0",
      cache: false,
    })`
```

and it should work.

Explanation:
In the past paths to modules used to be interpreted as being "relative" by default if they where not detected to be absolute. This was lately changed to the opposite to be able to load UMD-compatible libs (and their dependencies) directly without any changes.

I'll update the docs and make that clear.

**Comment by KoinBanks** [comment]
Thanks! :)

**Comment by dlueth** [comment]
@iFarmGolems Happy to help you out! Feel free to contact me directly if you need further assitance or open another issues if you encounter something you think might be a bug ;)
